export const FETCH_LIFESTYLE_REQUEST = "FETCH_LIFESTYLE_REQUEST";
export const FETCH_LIFESTYLE_SUCCESS = "FETCH_LIFESTYLE_SUCCESS";
export const FETCH_LIFESTYLE_FAILURE = "FETCH_LIFESTYLE_FAILURE";

export const FETCH_LIFESTYLE_OPTIONS_REQUEST = "FETCH_LIFESTYLE_OPTIONS_REQUEST";
export const FETCH_LIFESTYLE_OPTIONS_SUCCESS = "FETCH_LIFESTYLE_OPTIONS_SUCCESS";
export const FETCH_LIFESTYLE_OPTIONS_FAILURE = "FETCH_LIFESTYLE_OPTIONS_FAILURE";

export const USER_LIFESTYLE_REQUEST = "USER_LIFESTYLE_REQUEST";
export const USER_LIFESTYLE_SUCCESS = "USER_LIFESTYLE_SUCCESS";
export const USER_LIFESTYLE_FAILURE = "USER_LIFESTYLE_FAILURE";