export const NOTIFICATION_FETCH_REQUEST = "NOTIFICATION_FETCH_REQUEST";
export const NOTIFICATION_FETCH_SUCCESS = "NOTIFICATION_FETCH_SUCCESS";
export const NOTIFICATION_FETCH_FAILURE = "NOTIFICATION_FETCH_FAILURE";

export const NOTIFICATION_UNREAD_REQUEST = "NOTIFICATION_UNREAD_REQUEST";
export const NOTIFICATION_UNREAD_SUCCESS = "NOTIFICATION_UNREAD_SUCCESS";

export const NOTIFICATION_MARK_READ_REQUEST = "NOTIFICATION_MARK_READ_REQUEST";

export const NOTIFICATION_REMOVE= "NOTIFICATION_REMOVE";