export const OTHER_USER_FETCH_REQUEST = "OTHER_USER_FETCH_REQUEST";
export const OTHER_USER_FETCH_SUCCESS = "OTHER_USER_FETCH_SUCCESS";
export const OTHER_USER_FETCH_FAILURE = "OTHER_USER_FETCH_FAILURE";
