export const AUDIO_CALL_REQUEST = "AUDIO_CALL_REQUEST";
export const AUDIO_CALL_SUCCESS = "AUDIO_CALL_SUCCESS";
export const AUDIO_CALL_FAILED  = "AUDIO_CALL_FAILED";
export const AUDIO_CALL_RESET   = "AUDIO_CALL_RESET";
