export const PROFILE_IMAGE_UPLOAD_REQUEST = "PROFILE_IMAGE_UPLOAD_REQUEST";
export const PROFILE_IMAGE_UPLOAD_SUCCESS = "PROFILE_IMAGE_UPLOAD_SUCCESS";
export const PROFILE_IMAGE_UPLOAD_FAILED = "PROFILE_IMAGE_UPLOAD_FAILED";

export const PROFILE_IMAGE_DELETE_REQUEST = "PROFILE_IMAGE_DELETE_REQUEST";
export const PROFILE_IMAGE_DELETE_SUCCESS = "PROFILE_IMAGE_DELETE_SUCCESS";
export const PROFILE_IMAGE_DELETE_FAILED = "PROFILE_IMAGE_DELETE_FAILED";